task:
  name: "Two-step task"
  description: |
    A sequential decision-making task where participants make two choices per trial.
  goal: "Infer the cognitive model that best explains participant behavior."
  instructions: "Participants choose between two spaceships and interact with aliens for rewards."
  extra: "Task includes both model-based and model-free influences."

data:
  path: "data/two_step_participants.csv"
  id_column: "participant_id"
  input_columns: ["spaceship", "planet", "alien", "reward"]
  data2text_function: "narrative"
  narrative_template: |
    The participant chose spaceship {spaceship} and ended up on the {planet} Planet.
    The participant asked the alien {alien} and received {reward} coins.

llm:
  base_model: "Meta-Llama-3.1-70B-Instruct"
  temperature: 0.7
  max_tokens: 2048
  guardrails:
    - "Define a function named cognitive_model"
    - "Accept task data as input arguments"
    - "Return the negative log-likelihood"
    - "List parameters as a Python list"

evaluation:
  metric: "BIC"
  fitting_method: "scipy_minimize"
  best_model_path: "models/generated/best_model.py"
